# This module holds message mappings as specified in Java classes

package BudsPlusMsgs;
our %m;

$m{Msg} = {
  EOM => -35,
  INDEX_HEADER => 1,
  INDEX_PAYLOAD_START => 3,
  INDEX_SOM => 0,
  LENGTH_CRC => 2,
  LENGTH_EOM => 1,
  LENGTH_HEADER => 2,
  LENGTH_MSG_ID => 1,
  LENGTH_SOM => 1,
  PARAM_OFF => 0,
  PARAM_ON => 1,
  RESULT_FAILURE => 1,
  RESULT_SUCCESS => 0,
  SOM => -3,
};

$m{MsgID} = {
  ADJUST_SOUND_SYNC => -123,
  AMBIENT_MODE_UPDATED => -127,
  AMBIENT_VOLUME => -124,
  AMBIENT_WEARING_STATUS_UPDATED => -119,
  EQUALIZER => -122,
  EXTENDED_STATUS_UPDATED => 97,
  EXTRA_HIGH_AMBIENT => -106,
  FIND_MY_EARBUDS_START => -96,
  FIND_MY_EARBUDS_STOP => -95,
  FOTA_DEVICE_INFO_SW_VERSION => -76,
  GAME_MODE => -121,
  LOCK_TOUCHPAD => -112,
  MANAGER_INFO => -120,
  MSG_ID_DEBUG_GET_ALL_DATA => 38,
  MSG_ID_DEBUG_SERIAL_NUMBER => 41,
  MSG_ID_DEBUG_SKU => 34,
  MSG_ID_FOTA2_CONTROL => -68,
  MSG_ID_FOTA2_DOWNLOAD_DATA => -67,
  MSG_ID_FOTA2_EMERGENCY => -70,
  MSG_ID_FOTA2_OPEN => -69,
  MSG_ID_FOTA2_UPDATE => -66,
  MSG_ID_FOTA_CONTROL => -79,
  MSG_ID_FOTA_DOWNLOAD_DATA => -78,
  MSG_ID_FOTA_SESSION => -80,
  MSG_ID_FOTA_UPDATED => -77,
  MSG_ID_LOG_COREDUMP_COMPLETE => 51,
  MSG_ID_LOG_COREDUMP_DATA => 50,
  MSG_ID_LOG_COREDUMP_DATA_DONE => 56,
  MSG_ID_LOG_COREDUMP_DATA_SIZE => 49,
  MSG_ID_LOG_SESSION_CLOSE => 59,
  MSG_ID_LOG_SESSION_OPEN => 58,
  MSG_ID_LOG_TRACE_COMPLETE => 54,
  MSG_ID_LOG_TRACE_DATA => 53,
  MSG_ID_LOG_TRACE_DATA_DONE => 57,
  MSG_ID_LOG_TRACE_ROLE_SWITCH => 55,
  MSG_ID_LOG_TRACE_START => 52,
  MSG_ID_OUTSIDE_DOUBLE_TAP => -107,
  MSG_ID_SELF_TEST => -85,
  MSG_ID_SET_IN_BAND_RINGTONE => -118,
  MSG_ID_UPDATE_TIME => -89,
  MUTE_EARBUD => -94,
  MUTE_EARBUD_STATUS_UPDATED => -93,
  RESET => 80,
  SAMPLE => -1,
  SET_AMBIENT_MODE => -128,
  SET_SIDETONE => -117,
  SET_TOUCHPAD_OPTION => -110,
  STATUS_UPDATED => 96,
  TOUCHPAD_OTHER_OPTION => -109,
  TOUCH_UPDATED => -111,
  USAGE_REPORT => 64,
  VERSION_INFO => 99,
  VOICE_NOTI_STATUS => -92,
  VOICE_NOTI_STOP => -91,
};

$m{MsgExtendedStatusUpdated} = {
  DEVICE_COLOR_BLACK => 2,
  DEVICE_COLOR_PINK => 4,
  DEVICE_COLOR_WHITE => 0,
  DEVICE_COLOR_YELLOW => 3,
};

$m{CardEarbuds} = {
  COMMON_BATTERY_RANGE => 15,
  EARBUD_COLOR_BLACK => 260,
  EARBUD_COLOR_BLUE => 258,
  EARBUD_COLOR_DEEP_BLUE => 264,
  EARBUD_COLOR_NULL => -1,
  EARBUD_COLOR_OLYMPIC => 265,
  EARBUD_COLOR_PINK => 259,
  EARBUD_COLOR_PURPLE => 266,
  EARBUD_COLOR_RED => 263,
  EARBUD_COLOR_THOM_BROWNE => 262,
  EARBUD_COLOR_WHITE => 261,
  EARBUD_PLACEMENT_IN_OPEN_CASE => 3,
};

$m{CardEqualizer} = {
  Normal => 0,
  BassBoost => 1,
  Soft => 2,
  Dynamic => 3,
  Clear => 4,
  TrebleBoost => 5,
};

$m{TouchpadActivity} = {
  LEFT_OPTION => 0,
  OPTION1_BIXBY => 1,
  OPTION2_AMBIENT_SOUND => 2,
  OPTION3_VOLUME => 3,
  OPTION4_OTHERS => 4,
  OPTION4_OTHERS_LEFT => 5,
  OPTION4_OTHERS_RIGHT => 6,
  OPTION4_SPOTIFY => 4,
  RIGHT_OPTION => 1,
};

$m{MsgVersionInfo} = {
  SWRelVer => ["G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
  SWYear => ["O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
  SWMonth => ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"],
};
